### ISSUE TITLE
README example should use interpolation instead of indexing

### ISSUE THREAD

**Issue by ErikQQY** [SciML/BoundaryValueDiffEq.jl#107]
While trying ```MIRK``` solvers and ```Shooting``` solvers with example problem in README, the two kinds of solvers gave two different solutions:

```julia
using BoundaryValueDiffEq, OrdinaryDiffEq
function simplependulum!(du, u, p, t)
    θ = u[1]
    dθ = u[2]
    du[1] = dθ
    du[2] = -9.81 * sin(θ)
end
function bc!(residual, u, p, t)
    residual[1] = u[end ÷ 2][1] + pi / 2
    residual[2] = u[end][1] - pi / 2
end
tspan = (0.0, pi / 2)
prob = BVProblem(simplependulum!, bc!, [pi / 2, pi / 2], tspan)
mirk_sol = solve(prob, MIRK4(), dt = 0.05)
shooting_sol = solve(prob, Shooting(Tsit5()), dt=0.05)
```

Solution from MIRK(**Correct**):

![mirk_sol](https://github.com/SciML/BoundaryValueDiffEq.jl/assets/52615090/76ef98a1-2ab9-400f-9191-3786492f6613)

Solution from Shooting(**Wrong**):

![shooting_sol](https://github.com/SciML/BoundaryValueDiffEq.jl/assets/52615090/acdfa0da-0822-461c-a0c1-f07b6d37ee5f)

**Comment by ChrisRackauckas** [comment]
The issue is more that the model is a bit nonsense and you're not testing what the model is actually saying. You're testing that the value in the middle has a value, i.e.:

```julia
function bc!(residual, u, p, t)
    residual[1] = u(0.75)[1] + pi / 2
    residual[2] = u[end][1] - pi / 2
end
```

But that's not the model. The model is that the middle of the solve array is `pi / 2`. But the solver time steps are adaptive, so there's no guarantee that `u(0.75) == u[end ÷ 2]`, nor should one ever expect that to be true. We should just change this example to use interpolation.

**Comment by ErikQQY** [comment]
> The issue is more that the model is a bit nonsense and you're not testing what the model is actually saying.

Yeah, we should not expect the value in the middle to be the same since the adaptive time steppings, but the two solutions from different solvers are quite different, I think there is something wrong about this, especially the shooting method.

**Comment by ChrisRackauckas** [comment]
There's nothing wrong about the solutions. The `bc!` is just not a good definition. Change the `bc!`.

**Comment by ErikQQY** [comment]
Oh I see, I will propose a better example for the detailed usage of BVP solvers.

> We should just change this example to use interpolation.

I remembered OrdinaryDiffEq.jl can use interpolations, is there some text we can refer to add this feature to MIRK solvers?

**Comment by ChrisRackauckas** [comment]
No, this is a good example, it's just that every multi-point example should use interpolation.

> is there some text we can refer to add this feature to MIRK solvers?

The MIRK solvers already define the interpolation for the residual calculation.
