### ISSUE TITLE
MIRK4 adaptive time steps

### ISSUE THREAD

**Issue by sebastiantk** [SciML/BoundaryValueDiffEq.jl#172]
Hi, 

I am defining a TwoPointBVProblem and use
```
solve(prob, MIRK4(), dt = 1e-1, adaptive =true)
```
to solve it. However, the step size is not adjusted and remains at 0.01. 

Am I specifying this incorrectly? From what I understood #89 added this functionality.

Thank you!

**Comment by ErikQQY** [comment]
The adaptivity in MIRK solvers can automatically adapt the mesh according to the quality of numerical solution, could you please share your MWE and `]st`?

**Comment by sebastiantk** [comment]
I am not sure yet where exactly the problem lies in my case, so I will take the official example. 

```
using BoundaryValueDiffEq
using Plots
const g = 9.81
L = 1.0
tspan = (0.0, pi / 2)
function simplependulum!(du, u, p, t)
    θ = u[1]
    dθ = u[2]
    du[1] = dθ
    du[2] = -(g / L) * sin(θ)
end

function bc2a!(resid_a, u_a, p) # u_a is at the beginning of the time span
    resid_a[1] = u_a[1] + pi / 2 # the solution at the beginning of the time span should be -pi/2
end
function bc2b!(resid_b, u_b, p) # u_b is at the ending of the time span
    resid_b[1] = u_b[1] - pi / 2 # the solution at the end of the time span should be pi/2
end
bvp2 = TwoPointBVProblem(simplependulum!, (bc2a!, bc2b!), [pi / 2, pi / 2], tspan;
    bcresid_prototype=(zeros(1), zeros(1)))
sol3 = solve(bvp2, MIRK4(), dt=0.5, adaptive=true)

plot(sol2.t, reduce(hcat, sol2.u)')
plot!(sol3.t, reduce(hcat, sol3.u)')
```

Using the larger 0.5 timestep the solver still returns Success but the solutions are completely different. The timestep is adapted to approximately 0.1. 

What I was hoping for and what I think might be a problem in my use case is that the grid is adapted uniformly instead of making the grid denser in areas where the change in the function is greater.

**Comment by ErikQQY** [comment]
Both the solutions you mentioned are the true solutions to the example problem.

IIRC, the mesh refinement routine in MIRK solvers indeed returns uniform mesh. The MIRK solvers don't support grid coarsing for now.

**Comment by sebastiantk** [comment]
Not sure I understand - I get two different solutions:
![simple_pendulum](https://github.com/SciML/BoundaryValueDiffEq.jl/assets/40293032/54eb303a-4cd0-46ae-a846-12f16f426af9)

Both are correct?

**Comment by ErikQQY** [comment]
When we are constructing a boundary value problem using ```BVProblem``` or ```TwoPointBVProblem```, ```u0=[pi/2, pi/2]``` is just the initial guess, the side condition of this problem is only the two boundary condition specified in $u=0$ and $u=\pi/2$. The returned numerical solutions you mentioned both satisfy the differential equations and boundary conditions, so the solver would return a successful return code and terminate the solving.

**Comment by sebastiantk** [comment]
Ah, I have erroneously assumed that the uniqueness of an initial value problem translates to a boundary value problem - thank you for pointing this out!

Thank you for answering my question!
