### ISSUE TITLE
Passing parameters to the residuals method

### ISSUE THREAD

**Issue by BeastyBlacksmith** [SciML/BoundaryValueDiffEq.jl#23]
It would be convenient to have access to the parameters of the differential equations within the `residuals` method ( as well as the timespan ).
In the optimal case even for the initial value vector ( 3rd parameter of `TwoPointBVProblem` ).

**Comment by ChrisRackauckas** [comment]
For a `Shooting` method, you can get the parameters via `sol.prob.f.params` or `sol.prob.f.A` (not macro / macro).

For `GeneralMIRK` we would need to add the parameters to the rootfinding vector, which is possible and not difficult. For `MIRK4` etc. we would have to change the structure of the Jacobian (which is what MATLAB does with `bvp4c` and `bvp5c`). 

Then I think we can do a breaking change which adds a parameter vector to the `residuals` function arguments in `TwoPointBVProblem` and `BVProblem`

**Comment by avik-pal** [comment]
Currently the residuals take in `p` as an argument.
