### ISSUE TITLE
Deprecated use of `NonlinearSolve.LineSearch`

### ISSUE THREAD

**Issue by AayushSabharwal** [SciML/BoundaryValueDiffEq.jl#243]
BoundaryValueDiffEq seems to use deprecated functionality. This prevents it from precompiling with `--depwarn=error` which breaks any CI run that uses BVDiffEq. The depwarn can be seen in https://github.com/SciML/SymbolicIndexingInterface.jl/actions/runs/11813408749/job/32910396150#step:6:1899.

**Comment by ErikQQY** [comment]
BoundaryValueDiffEq.jl is not updated to the latest NonlinearSolve.jl, which is now using line search algorithms from LineSearch.jl. It can be fixed in #238
