### ISSUE TITLE
True banded matrix support

### ISSUE THREAD

**Issue by YingboMa** [SciML/BoundaryValueDiffEq.jl#31]
Open this issue for keeping track of upstream issue/PR. https://github.com/JuliaNLSolvers/NLsolve.jl/issues/113 & https://github.com/JuliaNLSolvers/NLsolve.jl/pull/125.

**Comment by pkofod** [comment]
Yeah, should be coming soon (didn't notice this issue before now). It will come in the form of users being able to supply their preferred Jacobian type (instance right now, but if that's bad then I'd love comments).

It would be great if you could provide an example with functions (f!, j!, fj!) and types for `F`, `J`, and `x` you would want this to work for.

**Comment by pkofod** [comment]
Merged but not tagged, I would still love an example! :)

**Comment by YingboMa** [comment]
Sorry for the late reply. It is hard to make a small example because the purpose of this package is to construct `f!` and `fj!`. Also, I cannot construct `j!` without explicitly calculate `f!`. Currently, `fj!` is computed in https://github.com/JuliaDiffEq/BoundaryValueDiffEq.jl/blob/master/src/jacobian.jl. But in essence, I am doing something like https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/pull/14#issue-251508485.
