### ISSUE TITLE
BigFloat support for TwoPointBVProblem using MIRK4

### ISSUE THREAD

**Issue by seadra** [SciML/BoundaryValueDiffEq.jl#43]
Using BigFloat with a TwoPointBVProblem and MIRK4 solver currently fails with the following error:

> ArgumentError: matrix type SparseArrays.SparseMatrixCSC{BigFloat,Int64}not supported. Try lu(convert(SparseMatrixCSC{Float64/ComplexF64,Int}, A)) for sparse floating point LU using UMFPACK or lu(Array(A)) for generic dense LU.

**Comment by ChrisRackauckas** [comment]
We probably just need to add a dependency on GenericSVD.jl

**Comment by seadra** [comment]
I naively tried using GenericSVD in my code but it didn't work, so I'm guessing that means something else :)

**Comment by avik-pal** [comment]
I thought `BigFloat` would just work, but seems like the problem is more fundamental

```julia
julia> similar(rand(BigFloat, 2, 3))
2×3 Matrix{BigFloat}:
 #undef  #undef  #undef
 #undef  #undef  #undef
```

This makes all of the internal NonlinearSolve machinery fail because it often performs concatenation and such on a `similar`ed array before assigning values to it.

**Comment by ChrisRackauckas** [comment]
For safety, just zero?

**Comment by avik-pal** [comment]
yes probably that's the way to go, it just needs to be added at quite a few places in NonlinearSolve

**Comment by avik-pal** [comment]
NonlinearSolve now supports bigfloats natively. Need to add a test for this here.
