### ISSUE TITLE
Solution has no du component

### ISSUE THREAD

**Issue by seadra** [SciML/BoundaryValueDiffEq.jl#44]
When using TwoPointBVProblem with MIRK4, the output solution doesn't contain a du field.

**Comment by seadra** [comment]
To clarify the issue, I'm following the [docs](https://docs.juliadiffeq.org/latest/basics/solution.html) which suggest the existence of such a field.

**Comment by ChrisRackauckas** [comment]
Yes it currently seems to be missing. We should add this.

**Comment by avik-pal** [comment]
We return an ODESolution for Shooting now. Should we populate the `original` field with the solution for the internal nonlinear solve solution?

**Comment by ChrisRackauckas** [comment]
Yes, that would be good to store

**Comment by avik-pal** [comment]
I just realized ODESolution doesn't have that field.
