### ISSUE TITLE
Adaptivity in MIRK solver

### ISSUE THREAD

**Issue by seadra** [SciML/BoundaryValueDiffEq.jl#54]
(I'm not sure to what extent this overlaps with #12 which mentions defects)

The possibility of having this was mentioned in this [blog post](https://juliadiffeq.org/2019/06/06/StiffSDEs.html):

> Adaptivity in the MIRK BVP solvers

Lack of adaptivity strongly limits the usability in any real use. (For example, I currently rely on Mathematica for BVPs.)

Any hopes we will have adaptivity in a near future?

**Comment by ChrisRackauckas** [comment]
The repo is setup for it, and the method itself can be adaptive, it's just no one ever got to it. If @yingboma finds time it might be a good time to finish it up. It just needs three steps: the definition of the interpolation, then the calculation of error estimates, then a resizing. It's not very difficult, but our main priority has been IVPs for awhile. As our work on stiff IVPs is starting to wrap up, this is a nice thing to keep in mind as an easy thing to finish up.

**Comment by jibaneza** [comment]
This together with #27 would increase a lot the usability of this package. Or maybe it would easier to implement the ODEInterface BVP solvers within the DifferentialEquations package?

**Comment by ChrisRackauckas** [comment]
Indeed. I am planning to look for covering it in the next GSoC round.
