### ISSUE TITLE
Residual vector dimension

### ISSUE THREAD

**Issue by homocomputeris** [SciML/BoundaryValueDiffEq.jl#55]
In BVProblem, can the `residual` vector have dimension larger that the dimension of `u`?

Alternatively, if I want to solve a `TwoPointBVProblem` for a state vector of dimension 10, and I have BCs on 6 variables at `t[0]` and on 6 variables at `t[end]`, how do I code the residual vector of dimension 12?
 
 For example, if I add an additional condition to the pendulum from the docs
 ```julia
using DifferentialEquations
using Plots

const g = 9.81
L = 1.0
tspan = (0.0,pi/2)
function simplependulum!(du,u,p,t)
    θ  = u[1]
    dθ = u[2]
    du[1] = dθ
    du[2] = -(g/L)*sin(θ)
end

 function bc1!(residual, u, p, t) # u[1] is the beginning of the time span, and u[end] is the ending
     residual[1] = u[1][1] + 1 
     residual[2] = u[end][1] - 1 
     residual[3] = u[end][2] + 2 # from the plot you can see that this is realistic
 end

bvp1 = BVProblem(simplependulum!, bc1!, [pi/2,pi/2], tspan)
sol1 = solve(bvp1, Shooting(Tsit5()))
plot(sol1)
 ```
 the solver casts `BoundsError: attempt to access 2-element Core.Array{Float64,1} at index [3]`

**Comment by ChrisRackauckas** [comment]
Is it possible for Newton's method to solve the nonlinear system when it has more constraints than variables? I think you'd generally have to interpret it in the L2 sense instead?

**Comment by homocomputeris** [comment]
Well, yeah.
Does DiffEq exclusively use Newton's? BVP solvers use NLsolve, don't they? Does NLsolve provide anything else like Matlab's `fsolve`?

Basically, my question comes from adapting a Matlab cruft for the problem in #52 which is solved with `fsolve`. I hoped I could use the high-level abstractions of BVP instead of rewriting everything.

Sorry for double posting here and on Gitter. Could you consider mentioning this dimension match thing in the docs?

**Comment by ChrisRackauckas** [comment]
>Does DiffEq exclusively use Newton's? BVP solvers use NLsolve, don't they? Does NLsolve provide anything else like Matlab's fsolve?

Does `fsolve` allow systems with more equations than variables? What algorithm is it using there? If it's possible we'll get it done.

**Comment by homocomputeris** [comment]
To be honest, I'm not familiar with the depths of Matlab. It seems that [`fsolve` with Levenberg–Marquardt](https://www.mathworks.com/help/optim/ug/equation-solving-algorithms.html#brrx7_e-1) (which multiplies J by its transpose, so non-square systems is not a problem) is automatically used to solve such problems:
```matlab
function F = root2d(x)
F(1) = exp(-exp(-(x(1)+x(2)))) - x(2)*(1+x(1)^2);
F(2) = x(1)*cos(x(2)) + x(2)*sin(x(1)) - 0.5;
F(3) = x(1)^2 + x(2)^2 - 2;
end
```
```matlab
clear all;
fun = @root2d;
x0 = [0,0];
x = fsolve(fun,x0)
```
```
Warning: Trust-region-dogleg algorithm of FSOLVE cannot handle non-square systems; using Levenberg-Marquardt algorithm instead. 
> In fsolve (line 316) 

No solution found.

fsolve stopped because the last step was ineffective. However, the vector of function
values is not near zero, as measured by the value of the function tolerance. 
x =    0.2447    1.3199
```

The algorithm I'm translating in Julia, `fsolve` used to minimize the 2-point BVP residual with 7 values fixed on the left and 7 on the right (14 BCs total) while the state vector has dimension 13, so there are 6 variables. And for that problem it produces realistic results.

Matlab references:
- Levenberg, K., “A Method for the Solution of Certain Problems in Least-Squares,” Quarterly Applied Mathematics 2, pp. 164-168, 1944.
- Marquardt, D., “An Algorithm for Least-squares Estimation of Nonlinear Parameters,” SIAM Journal Applied Mathematics, Vol. 11, pp. 431-441, 1963.
- Moré, J. J., “The Levenberg-Marquardt Algorithm: Implementation and Theory,” Numerical Analysis, ed. G. A. Watson, Lecture Notes in Mathematics 630, Springer Verlag, pp. 105-116, 1977.

**Comment by ChrisRackauckas** [comment]
Yeah that's an L2 minimization, not a linear solve, which gives "exact" f(x)=0. That might be the only way to interpret it though?

**Comment by homocomputeris** [comment]
If this 'non-exact' solution eventually satisfies the BVP, it should be fine, I think.

**Comment by ChrisRackauckas** [comment]
@YingboMa have you looked into this?

**Comment by avik-pal** [comment]
This is handled currently. The user needs to pass in an NLLS solvers. Eventually once we have default solvers for NLLS in NonlinearSolve, the switching will be automatic!
