### ISSUE TITLE
Add nonstandard array support

### ISSUE THREAD

**Issue by jonniedie** [SciML/BoundaryValueDiffEq.jl#67]
It seems that [`BVPSystem` requires plain old `Vector`s](https://github.com/SciML/BoundaryValueDiffEq.jl/blob/012942faad4bea1896eaed047e35b8ef00444097/src/BoundaryValueDiffEq.jl#L26). Any way to lift this restriction for `ComponentArray`s and other nonstandard arrays?

**Comment by ChrisRackauckas** [comment]
It's just old code. It should get updated to be generic.

**Comment by avik-pal** [comment]
It should support non-standard arrays now. Feel free to open an issue if any particular array type doesn't propagate correctly.
