### ISSUE TITLE
MIRK4() BVP solver gives wrong results

### ISSUE THREAD

**Issue by Ickaser** [SciML/BoundaryValueDiffEq.jl#69]
Here is a MWE. Solving an ODE very similar to the Blasius problem (boundary layers in fluid mechanics), as written below:
```
using DifferentialEquations
using Plots
# ODE
function bleq!(du, u, p, t)
    g, h, k = u
    dg = h
    dh = k
    dk = -g*k  + h^2  - 1
    du[1] = dg
    du[2] = dh
    du[3] = dk
end

# IC: let g = 0, h = 0. 
# BC: at large η, g' = 1
function bc!(resid, u, p, t)
#     k, h, g = 
    resid[1] = u[1][1] # g=0 at t=0
    resid[2] = u[1][2] # g'=0 at t=0
    resid[3] = u[end][2] - 1.0 #g'=1 at t=end
end
# Guessed IC?
icg = [0, 0, 1.2]
ηsp = (0.0, 10.0)
bvp = BVProblem(bleq!, bc!, icg, ηsp)

@time sol = solve(bvp, Shooting(Tsit5()), dt=0.5)

plot(sol, labels=permutedims(["g", "g'", "g''"]), legend=:topleft)
```

As written, with `Shooting(Tsit5())`, the problem solves correctly and my plot results look like
![image](https://user-images.githubusercontent.com/47340776/141860974-b3bb52b6-c9cf-49eb-9932-c6448d59037b.png)
When I replace the solver with `MIRK4()`, as recommended by https://diffeq.sciml.ai/stable/solvers/bvp_solve/ , I get
![image](https://user-images.githubusercontent.com/47340776/141861076-2e3bb98c-7690-47b1-a7b5-038f1981b3fa.png)

**Comment by ChrisRackauckas** [comment]
Worth looking into. I want to try and get a BVP GSoC for this. My guess is that it might just be an instability for large dt, as Tsti5 is adaptive but MIRK4 right now is not (and the GSoC would make it adaptive)

**Comment by Ickaser** [comment]
I think it's more wrong than just an instability. When I crank down the dt for MIRK4 it approaches an identical solution.

With the same code as above, I find:
```
solS = solve(bvp, Shooting(Tsit5()), dt=0.5)
solM = solve(bvp, MIRK4(), dt=0.01)
```

Shooting gives
![image](https://user-images.githubusercontent.com/47340776/143151378-1925d500-99a2-4a44-81de-e898db97e28c.png)
while MIRK4 gives
![image](https://user-images.githubusercontent.com/47340776/143151397-6bb55978-021f-4063-8947-203c238784fb.png)

If I am understanding correctly that the returned time points from `solve` are those used by the adaptive algorithm, the explicit method is getting by with time steps that hover around `dt=0.3`, while even with `dt=0.01` MIRK4 stays wrong.

**Comment by ChrisRackauckas** [comment]
What about one order lower? Or two? If it doesn't converge then that's odd.

**Comment by Ickaser** [comment]
Here's a 2nd order problem, still nonlinear; both methods seem to work fine. (At first I thought it wasn't working, but it looks like as long as I do my math right it's behaving like it should.)

```
function bleq2!(du, u, p, t)
    g, h = u
    dg = h
    dh = -1/2*g*h  
    du[1] = dg
    du[2] = dh
end
function bc2!(resid, u, p, t)
#     k, h, g = 
    resid[1] = u[1][1] - 2   # g=2 at t=0
    resid[2] = u[end][1] - 1 # g=1 at t=end
#     resid[2] = u[end][2] # g'=0 at t=end
end

icg = [2, -4.5]
tsp = (0.0, 2.0)
bvp2 = BVProblem(bleq2!, bc2!, icg, tsp)

@time solS = solve(bvp2, Shooting(Tsit5()), dt=0.5)
@time solM = solve(bvp2, MIRK4(), dt=0.1)
```
```
  1.331397 seconds (2.14 M allocations: 106.853 MiB, 1.48% gc time)
  0.245008 seconds (2.54 M allocations: 214.080 MiB, 21.60% gc time)
```
![image](https://user-images.githubusercontent.com/47340776/143924472-9c71625c-d86f-4165-a2c2-4865f0cd5eb0.png)

**Comment by avik-pal** [comment]
`MIRK4()` with adaptivity seems to give the right answer now
