### ISSUE TITLE
BV Problem : No possibility to provide non constant initial guess

### ISSUE THREAD

**Issue by NilsBruch** [SciML/BoundaryValueDiffEq.jl#73]
According to the tutorial on BVP "The third argument of BVProblem is the initial guess of the solution, which is constant in this example.". For the pendulum example (which is a 2nd order dgl) you have to provide two initial guesses, e.g. u0=[0,5]. But what to do if one would like to provide a non constant initial guess such as u0[sin(t),cos(t)]? Then one would provide u0 as u0=[[0,0],[1,1],[n,n]] where n is the desired length of the solution. But this approach throws an error "DimensionMismatch("tried to assign n elements to 2 destinations")". Here is a working example that shows this error

[nonConstantIntialGuessError.txt](https://github.com/SciML/DifferentialEquations.jl/files/8852976/nonConstantIntialGuessError.txt)

**Comment by morningglory05** [comment]
This is something that I am trying to apply to the current work I am doing. However, when I run my code, and when I run the code in the provided .txt file I get the error "MethodError: no method matching zero(::Type{Vector{Float64}})". Any ideas why the errors are different?
