### ISSUE TITLE
Feature request: BVP-DAE support

### ISSUE THREAD

**Issue by JulianUlrich** [SciML/BoundaryValueDiffEq.jl#76]
It would be nice, if solving of boundary value problems for implicit or semi-explicit DAEs was supported. Such solvers exist in FORTRAN (COLDAE).

**Comment by ChrisRackauckas** [comment]
Agreed. First, we should add mass matrices to the BVProblem specification. It needs a BVPFunction, like the ODEFunciton, etc. to add such Jacobian and other metafunctions. That would get `mass_matrix`, so then linearly implicit BVP DAEs can be specified. Then yes we need to add that to the MIRK method.

**Comment by JulianUlrich** [comment]
Nice, i am looking forward to it. I am surprised this has not been implemented in any commercial tool...
